# 기본 AcademicPages 설정
title: "김우신"
email: "mkpark7165@gmail.com"
description: "한신대학교 AISW 계열 학생 포트폴리오 및 학술 페이지"
baseurl: ""
url: "https://woosin.github.io"
theme: academicpages

author:
  name: "김우신"
  avatar: "/images/profile.png"
  email: "mkpark7165@gmail.com"
  affiliations: "한신대학교, AISW 계열"

